#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication topoSet
runApplication makeFaMesh

#cp 0.org/* 0/ 
runApplication `getApplication`

#------------------------------------------------------------------------------
~                                                                               
~                                                                               
~                                        
